export const scheduleTabs = [
  {
    id: "panel-1",
    time: "07:00",
    label: "Bữa Sáng Dinh Dưỡng",
    title: "Khởi đầu ngày mới tràn đầy năng lượng",
    badge: "Bữa Sáng Dinh Dưỡng",
    badgeColor: "bg-accent-gold-light text-accent-gold",
    desc: "Hệ thống trục xoay silicone tự động định lượng chính xác 15g hạt khô. PurraFeed phát ra đoạn ghi âm giọng nói của bạn để kêu gọi thú cưng chạy lại thưởng thức bữa sáng nóng sốt, đúng giờ tạo thói quen tốt cho hệ tiêu hóa.",
    image: "/assets/images/purra_feed_breakfast.webp",
    activeColor: "text-accent-gold border-accent-gold",
    activeDot: "bg-accent-gold shadow-[0_0_0_6px_var(--color-accent-gold-light)] scale-[1.3]",
  },
  {
    id: "panel-2",
    time: "12:30",
    label: "Đàm Thoại & Camera HD",
    title: "Bữa trưa tràn ngập yêu thương",
    badge: "Đàm Thoại & Camera HD",
    badgeColor: "bg-accent-sage-light text-accent-sage",
    desc: "Khi bạn đang ở công sở hay đi du lịch, chỉ cần mở ứng dụng PuraPet. Camera HD 1080P góc rộng 130 độ sẽ hiển thị rõ nét khay thức ăn. Bạn có thể bật âm thanh đàm thoại 2 chiều để trò chuyện, vỗ về bé yêu ăn trưa một cách trực quan.",
    image: "/assets/images/purra_feed_lunch_app.webp",
    activeColor: "text-accent-sage border-accent-sage",
    activeDot: "bg-accent-sage shadow-[0_0_0_6px_var(--color-accent-sage-light)] scale-[1.3]",
  },
  {
    id: "panel-3",
    time: "18:00",
    label: "Hoạt Động Kép Thông Minh",
    title: "Bữa tối trộn hạt tươi ngon",
    badge: "Hoạt Động Kép Thông Minh",
    badgeColor: "bg-accent-coral-light text-accent-coral",
    desc: "Phục vụ bữa tối hấp dẫn trộn lẫn giữa hạt khô và hạt sấy thăng hoa (Freeze-dried) nhờ khay chia hạt kép lớn. Động cơ tự động đảo chiều xoay nếu phát hiện lực cản giúp hạt xả mượt mà, không bao giờ lo kẹt hạt.",
    image: "/assets/images/purra_feed_dinner_mix.webp",
    activeColor: "text-accent-coral border-accent-coral",
    activeDot: "bg-accent-coral shadow-[0_0_0_6px_var(--color-accent-coral-light)] scale-[1.3]",
  },
  {
    id: "panel-4",
    time: "22:00",
    label: "Khóa Thông Minh & Hồng Ngoại",
    title: "Giấc ngủ êm đềm, không lo trộm hạt",
    badge: "Khóa Thông Minh & Hồng Ngoại",
    badgeColor: "bg-[#6366F1]/10 text-[#6366F1]",
    desc: "Chế độ khóa nút bấm (Child Lock) tự động kích hoạt vào ban đêm để tránh mèo cưng dùng chân cào nút hạt rơi. Hệ thống camera hồng ngoại chuyển chế độ nhìn đêm thông minh, theo dõi sức khỏe mèo 24/7 không phát ánh sáng gây giật mình.",
    image: "/assets/images/purra_feed_night_vision.webp",
    activeColor: "text-[#6366F1] border-[#6366F1]",
    activeDot: "bg-[#6366F1] shadow-[0_0_0_6px_rgba(99,102,241,0.15)] scale-[1.3]",
  },
];
